"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

generate fib
find all even numbers
sum all even nubers and return that

"""

import logging

logging.basicConfig(level=logging.DEBUG)


def even_fib():
    fib_list = [1, 2]

    while fib_list[-1] < 4000000:
        fib_list.append(fib_list[-2] + fib_list[-1])

    del fib_list[-1]
    even_list = [x for x in fib_list if x % 2 == 0]

    return sum(even_list)

#print(even_fib())


logging.debug(even_fib())
